language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-kirby' ]; then cd .. && eval "mv $currentfolder generator-kirby" && cd generator-kirby; fi